package br.com.sw.planets.domain.document;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBDocument
public abstract class AbstractDocument {
	
	@JsonIgnore
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "id")
	private String id;
	
	@JsonIgnore
	@DynamoDBAttribute
	public String criationDate;
}
